apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-teams
spec:
  template:
    # serviceAccountName: argo-events-sa
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-Sensor
      eventSourceName: pod-watcher
      eventName: pod-events 
  triggers:  
    - template:
        name: http-trigger
        http:
          url: "<Webhook-Url>"  
          payload:
            - src:
                dependencyName: test-Sensor
              #   dataKey: body.status.phase
              # dest: text
                dataTemplate: |
                  The status of pod: **{{ .Input.body.metadata.name }}** is: **{{ .Input.body.status.phase }}**
              dest: text
          headers:  
            Content-Type: "application/json"
          method: "POST"
    #       # timeout: 3s
