apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-teams
spec:
  template:
    # serviceAccountName: argo-events-sa
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-Sensor
      eventSourceName: pod-watcher
      eventName: pod-events 
  triggers:  
    - template:
        name: http-trigger
        http:
          url: "https://aicgoveg.webhook.office.com/webhookb2/439176ce-9b86-490f-bb31-69550a39e224@f4343c2b-01ec-4cae-aded-5e9249898d12/IncomingWebhook/67d65ee20e994f7a9bdad27beea8fc65/605e58c3-eff4-46e2-9408-354e8741095d/V2NxDD-BlgANpF7pBtXwE_IzYk352qJdAqSjBF6ewJiKo1"  
          payload:
            - src:
                dependencyName: test-Sensor
                dataKey: body # Static value if dataKey is missing
              dest: text
            # - src:  # Add a static fallback or additional field
            #     dependencyName: test-Sensor
            #     dataKey: "Fallback message if no event data"  # Static value if dataKey is missing
            #   dest: text
          headers:  
            Content-Type: "application/json"
          method: "POST"
          # timeout: 3s
