## Still under testing

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-email
spec:
  template:
    serviceAccountName: argo-events-sa 
  dependencies:
    - name: test-sensor
      eventSourceName: pod-watcher
      eventName: pod-events
      # filters:  
      #   data:  
      #     - path: status.phase  
      #       type: string  
      #       value:  
      #         - "Running"  
      #         - "Pending"  
      #         - "Completed"  
  triggers:  
    - template:  
        name: pod-status-email-trigger  
        email:  
          host: "smtp.gmail.com"  
          port: 587  
          username: "<your-email@gmail.com>"  
          smtpPassword:  
            name: aic-secret 
            key: password
          from: ""  
          to:  
            - ""  
          subject: "Pod {{.pod_name}} Status Changed to {{.pod_phase}}"  
          body: |  
            Pod Details:  
            - Name: {{.pod_name}}  
            - Namespace: {{.pod_namespace}}  
            - Phase: {{.pod_phase}}  
            - Timestamp: {{.timestamp}}  
          parameters:  
            - src:  
                dependencyName: pod-sensor  
                dataKey: body.metadata.name  
              dest: pod_name  
            - src:  
                dependencyName: pod-sensor  
                dataKey: body.metadata.namespace  
              dest: pod_namespace  
            - src:  
                dependencyName: pod-sensor  
                dataKey: body.status.phase  
              dest: pod_phase